name: Test Email Step

on:
  push:
    branches:
      - main  # or the branch you want to trigger on

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: 22f3000780@ds.study.iitm.ac.in
        run: echo "Hello, world!"
